

[client_renderer]
enable_computational_server = false # if true, it needs computational_server.toml
graphics_window_enabled = false
window_mode = 1 # 0 - windowed, 1 - fullscreen
display_index = 2 # -1 - primary, actual index else
window_position = [340, 240] #in pixels [pos_x, pos_y] size_x, size_y]
window_size = [840, 540] # in pixels [pos_x, pos_y] size_x, size_y]

[client_renderer.visual_style]
color_nothing = [2.0, 2.0, 2.0, 2.0]
color_density_low = [3.0, 3.0, 3.0, 3.0]
color_density_high = [4.0, 4.0, 4.0, 4.0]